# Generated by Django 2.2.1 on 2019-05-25 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='ppic.jpg', upload_to='ppic/')),
                ('city', models.CharField(default='Indore', max_length=20, null=True)),
                ('country', models.CharField(default='Indiaa', max_length=20, null=True)),
                ('college', models.CharField(default='IIPS', max_length=20, null=True)),
                ('dob', models.DateField(max_length=20, null=True)),
                ('bio', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
