# Generated by Django 2.2.1 on 2019-05-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190521_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='ppic.jpg', upload_to='ppic'),
        ),
    ]
