# Generated by Django 2.0.13 on 2019-07-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msguser',
            old_name='msgemail',
            new_name='email',
        ),
    ]
