# Generated by Django 2.0.13 on 2019-07-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20190713_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msguser',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='msguser',
            name='msgusername',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
