# Generated by Django 2.2.2 on 2019-07-02 07:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('project', '0023_auto_20190702_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprodetal',
            name='project',
        ),
        migrations.RemoveField(
            model_name='userprodetal',
            name='user',
        ),
        migrations.DeleteModel(
            name='Userpro',
        ),
        migrations.DeleteModel(
            name='Userprodetal',
        ),
    ]
