# Generated by Django 2.2.2 on 2019-07-02 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('project', '0025_userpro_userprodetal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpro',
            name='current_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.DeleteModel(
            name='Userprodetal',
        ),
    ]
