# Generated by Django 2.2.2 on 2019-07-02 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('project', '0026_auto_20190702_1310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userpro',
        ),
    ]
