# Generated by Django 2.2.2 on 2019-07-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('project', '0028_userpro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpro',
            name='project',
            field=models.ManyToManyField(to='project.Project'),
        ),
    ]
