# Generated by Django 2.0.13 on 2019-07-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0053_auto_20190706_1214'),
        ('project', '0054_auto_20190708_1417'),
    ]

    operations = [
    ]
