# Generated by Django 2.0.13 on 2019-07-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0055_auto_20190711_1647'),
        ('project', '0055_merge_20190709_1819'),
    ]

    operations = [
    ]
