# Generated by Django 2.0.13 on 2019-07-27 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0060_auto_20190727_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_stat',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AlterField(
            model_name='project1',
            name='description',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='project1',
            name='prerequisite',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='project1',
            name='pro_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='protags',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AlterField(
            model_name='userpro',
            name='project',
            field=models.ManyToManyField(to='project.Project'),
        ),
    ]
