# Generated by Django 2.0.13 on 2019-07-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0063_auto_20190727_1144'),
        ('project', '0061_auto_20190727_1356'),
    ]

    operations = [
    ]
