# Generated by Django 2.2.3 on 2019-07-27 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('project', '0062_auto_20190727_1414'),
        ('project', '0067_auto_20190727_1450'),
    ]

    operations = [
    ]
