# Generated by Django 2.2.3 on 2019-08-26 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0075_auto_20190820_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='project1',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='project1',
            name='duration',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project1',
            name='slug',
            field=models.SlugField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pro_stat',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AlterField(
            model_name='protags',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AlterField(
            model_name='userpro',
            name='project',
            field=models.ManyToManyField(to='project.Project'),
        ),
        migrations.CreateModel(
            name='UserPro1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(null=True, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
