# Generated by Django 2.2.3 on 2019-08-26 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('project', '0078_auto_20190826_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_stat',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AlterField(
            model_name='protags',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AlterField(
            model_name='userpro',
            name='project',
            field=models.ManyToManyField(to='project.Project'),
        ),
        migrations.AlterField(
            model_name='userpro1',
            name='users',
            field=models.ManyToManyField(
                default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                          to=settings.AUTH_USER_MODEL), null=True, related_name='users',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
