# Generated by Django 2.2.2 on 2019-06-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20190627_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usrgroup',
            name='current_group',
        ),
        migrations.RemoveField(
            model_name='usrgroup',
            name='users',
        ),
        migrations.DeleteModel(
            name='Groupdetails',
        ),
        migrations.DeleteModel(
            name='Usrgroup',
        ),
    ]
