# Generated by Django 2.2.2 on 2019-07-01 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('project', '0021_auto_20190701_1521'),
        ('groups', '0005_groupdetails_usrgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_group',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Groupdetails')),
                ('project', models.ManyToManyField(to='project.Project')),
            ],
        ),
    ]
