# Generated by Django 2.2.2 on 2019-07-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('groups', '0006_progroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progroup',
            name='project',
            field=models.ManyToManyField(to='project.Project'),
        ),
    ]
