# Generated by Django 2.2.2 on 2019-07-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('groups', '0019_auto_20190703_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progroup',
            name='project',
            field=models.ManyToManyField(to='project.Project'),
        ),
    ]
