# Generated by Django 2.2.2 on 2019-07-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0023_groupdetails_progroup_usrgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progroup',
            name='project',
            field=models.ManyToManyField(to='project.Project'),
        ),
    ]
