# Generated by Django 2.2.2 on 2019-07-04 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0024_auto_20190704_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progroup',
            name='current_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Groupdetails', unique=True),
        ),
        migrations.AlterField(
            model_name='progroup',
            name='project',
            field=models.ManyToManyField(to='project.Project'),
        ),
    ]
