# Generated by Django 2.2.2 on 2019-07-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0025_auto_20190704_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdetails',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='progroup',
            name='project',
            field=models.ManyToManyField(to='project.Project'),
        ),
        migrations.AlterField(
            model_name='usrgroup',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
