# Generated by Django 2.2.2 on 2019-07-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0028_groupdetails_progroup_usrgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdetails',
            name='slug',
            field=models.SlugField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='progroup',
            name='project',
            field=models.ManyToManyField(to='project.Project'),
        ),
    ]
