# Generated by Django 2.2.2 on 2019-07-05 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0029_auto_20190705_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupdetails',
            name='slug',
        ),
        migrations.AddField(
            model_name='groupdetails',
            name='entrykey',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='groupdetails',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Closed')], default=0),
        ),
        migrations.AlterField(
            model_name='progroup',
            name='current_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Groupdetails'),
        ),
        migrations.AlterField(
            model_name='progroup',
            name='project',
            field=models.ManyToManyField(to='project.Project'),
        ),
    ]
