# Generated by Django 2.2.2 on 2019-07-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0030_auto_20190705_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdetails',
            name='image',
            field=models.ImageField(default='gpic', upload_to='gpic/'),
        ),
        migrations.AlterField(
            model_name='progroup',
            name='project',
            field=models.ManyToManyField(to='project.Project'),
        ),
    ]
