# Generated by Django 2.2.2 on 2019-07-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0031_auto_20190705_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progroup',
            name='current_group',
        ),
        migrations.RemoveField(
            model_name='progroup',
            name='project',
        ),
        migrations.RemoveField(
            model_name='usrgroup',
            name='current_group',
        ),
        migrations.RemoveField(
            model_name='usrgroup',
            name='users',
        ),
        migrations.DeleteModel(
            name='Groupdetails',
        ),
        migrations.DeleteModel(
            name='Progroup',
        ),
        migrations.DeleteModel(
            name='Usrgroup',
        ),
    ]
