# Generated by Django 2.2.2 on 2019-07-05 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0048_auto_20190705_1421'),
        ('groups', '0032_auto_20190705_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
                ('bio', models.TextField(max_length=250, null=True)),
                ('entrykey', models.CharField(max_length=20, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Closed')], default=0)),
                ('image', models.ImageField(default='gpic', upload_to='gpic/')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User', to=settings.AUTH_USER_MODEL)),
                ('project', models.ManyToManyField(to='project.Project')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
