# Generated by Django 2.2.2 on 2019-07-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0034_auto_20190705_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='group',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='group',
            name='entrykey',
        ),
        migrations.RemoveField(
            model_name='group',
            name='image',
        ),
        migrations.RemoveField(
            model_name='group',
            name='project',
        ),
        migrations.RemoveField(
            model_name='group',
            name='status',
        ),
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
    ]
