# Generated by Django 2.2.2 on 2019-07-05 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0051_auto_20190705_1440'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0035_auto_20190705_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='bio',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='entrykey',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(default='gpic', upload_to='gpic/'),
        ),
        migrations.AddField(
            model_name='group',
            name='project',
            field=models.ManyToManyField(null=True, to='project.Project'),
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Closed')], default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User', to=settings.AUTH_USER_MODEL), null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
