# Generated by Django 2.2.2 on 2019-07-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('groups', '0037_auto_20190705_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(default='gpic.jpg', upload_to='gpic/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='project',
            field=models.ManyToManyField(blank=True, to='project.Project'),
        ),
    ]
