# Generated by Django 2.0.13 on 2019-07-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0038_auto_20190706_1214'),
        ('groups', '0039_auto_20190708_1417'),
    ]

    operations = [
    ]
