# Generated by Django 2.0.13 on 2019-07-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0040_auto_20190711_1647'),
        ('groups', '0040_merge_20190709_1820'),
    ]

    operations = [
    ]
