# Generated by Django 2.2.3 on 2019-07-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('groups', '0044_auto_20190713_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='project',
            field=models.ManyToManyField(blank=True, to='project.Project'),
        ),
        migrations.AlterField(
            model_name='groupprojects',
            name='project',
            field=models.ManyToManyField(to='project.Project'),
        ),
    ]
