# Generated by Django 2.0.13 on 2019-07-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0046_auto_20190727_1356'),
        ('groups', '0048_auto_20190727_1144'),
    ]

    operations = [
    ]
