# Generated by Django 2.2.3 on 2019-08-06 05:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('groups', '0052_auto_20190727_1450'),
        ('groups', '0048_auto_20190727_1859'),
    ]

    operations = [
    ]
