# Generated by Django 2.2.3 on 2019-08-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('groups', '0053_merge_20190806_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='project',
            field=models.ManyToManyField(blank=True, to='project.Project'),
        ),
        migrations.AlterField(
            model_name='groupprojects',
            name='project',
            field=models.ManyToManyField(to='project.Project'),
        ),
    ]
