# Generated by Django 2.2.1 on 2019-05-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('email', models.TextField(max_length=30)),
                ('city', models.TextField(max_length=20)),
                ('country', models.TextField(max_length=20)),
                ('gender', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
