# Generated by Django 2.2.1 on 2019-05-20 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190518_1713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
