# Generated by Django 2.2.1 on 2019-05-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190520_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='ppic.jpeg', upload_to='ppic'),
        ),
    ]
