# Generated by Django 2.2.1 on 2019-05-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190521_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Indore', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.CharField(default='IIPS', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='India', max_length=20, null=True),
        ),
    ]
