# Generated by Django 2.2.3 on 2019-07-27 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=1024)),
                ('image', models.ImageField(null=True, upload_to='media/resources/img')),
                ('files', models.FileField(null=True, upload_to='media/resources/img')),
                ('links', models.URLField(null=True)),
                ('promoter', models.BooleanField(choices=[(True, 'Admin'), (False, 'User')], default=False)),
                ('language', models.CharField(max_length=10)),
                ('creator',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource_Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=25)),
                ('resources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Resources')),
            ],
        ),
    ]
