# Generated by Django 2.2.3 on 2019-08-06 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Resource_Platform',
        ),
        migrations.DeleteModel(
            name='Resources',
        ),
    ]
