# Generated by Django 2.2.3 on 2019-08-06 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0002_auto_20190806_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C/C++/c#', 'C/C++/c#'),
                                                       ('JavaScript', 'JavaScript')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reslink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=1024)),
                ('links', models.URLField()),
                ('promoter', models.BooleanField(choices=[(True, 'Admin'), (False, 'User')], default=False)),
                ('creator',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Resofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=1024)),
                ('files', models.FileField(upload_to='media/resources/img')),
                ('promoter', models.BooleanField(choices=[(True, 'Admin'), (False, 'User')], default=False)),
                ('creator',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Resoimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=1024)),
                ('image', models.ImageField(upload_to='media/resources/img')),
                ('promoter', models.BooleanField(choices=[(True, 'Admin'), (False, 'User')], default=False)),
                ('creator',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Resource_Platform_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=25)),
                ('resources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Reslink')),
            ],
        ),
        migrations.CreateModel(
            name='Resource_Platform_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=25)),
                ('resources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Resoimg')),
            ],
        ),
        migrations.CreateModel(
            name='Resource_Platform_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=25)),
                ('resources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Resofile')),
            ],
        ),
    ]
