# Generated by Django 2.2.3 on 2019-08-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resources',
         '0003_language_reslink_resofile_resoimg_resource_platform_file_resource_platform_img_resource_platform_lin'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='discription',
            field=models.TextField(default='', max_length=8042),
        ),
    ]
