# Generated by Django 2.2.3 on 2019-08-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resources', '0005_auto_20190806_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(
                choices=[('Python', 'Python'), ('Java', 'Java'), ('CFamily', 'CFamily'), ('JavaScript', 'JavaScript')],
                max_length=10),
        ),
        migrations.AlterField(
            model_name='resoimg',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
